### ADD FIRE INCIDENT
POST http://localhost:8085/api/fire-incidents
Content-Type: application/json

{
  "ward": "Ward 1",
  "district": "Rushinga",
  "province": "Mashonaland Central",
  "occurrenceDateTime": "2026-09-25T10:00:00",
  "reporter": "Akatendeka",
  "severity": "HIGH",
  "status": "PENDING",
  "latitude": -16.758,
  "longitude": 31.130,
  "areaBurnedHectares": 5.5,
  "suspectedCause": "ACCIDENTAL",
  "injuries": 2,
  "fatalities": 0,
  "structuresDestroyed": 1,
  "fireStatus": "ACTIVE"
}

### VIEW ALL
GET http://localhost:8085/api/fire-incidents

### VIEW ONE
GET http://localhost:8085/api/fire-incidents/1

### UPDATE
PUT http://localhost:8085/api/fire-incidents/1
Content-Type: application/json

{
  "ward": "Ward 1",
  "district": "Rushinga",
  "province": "Mashonaland Central",
  "occurrenceDateTime": "2026-09-25T10:00:00",
  "reporter": "Akatendeka",
  "severity": "MEDIUM",
  "status": "PENDING",
  "latitude": -16.758,
  "longitude": 31.130,
  "areaBurnedHectares": 7.0,
  "suspectedCause": "ACCIDENTAL",
  "injuries": 2,
  "fatalities": 0,
  "structuresDestroyed": 2,
  "fireStatus": "CONTAINED"
}

### APPROVE
PUT http://localhost:8085/api/fire-incidents/1/approve?user=supervisor

### REQUEST CORRECTION
PUT http://localhost:8085/api/fire-incidents/1/correction?user=supervisor&reason=Check%20location

### REJECT
PUT http://localhost:8085/api/fire-incidents/1/reject?user=supervisor&reason=Invalid%20report

### AUDIT HISTORY
GET http://localhost:8085/api/fire-incidents/1/audit

### DELETE
DELETE http://localhost:8085/api/fire-incidents/1
