server.port=8080

spring.application.name=dpdms-api-gateway

spring.cloud.gateway.routes[0].id=mining-accident-service
spring.cloud.gateway.routes[0].uri=http://localhost:8085
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/mining-accidents/**
logging.level.org.springframework.cloud.gateway=DEBUG

management.endpoints.web.exposure.include=health,info,metrics,gateway
management.endpoint.health.show-details=always
# Flood Service
spring.cloud.gateway.routes[1].id=flood-service
spring.cloud.gateway.routes[1].uri=http://localhost:8081g
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/floods/**

# Drought Service
spring.cloud.gateway.routes[2].id=drought-service
spring.cloud.gateway.routes[2].uri=http://localhost:8081
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/drought/**

# Fire Service
spring.cloud.gateway.routes[3].id=fire-service
spring.cloud.gateway.routes[3].uri=http://localhost:8084
spring.cloud.gateway.routes[3].predicates[0]=Path=/api/fires/**

# Zoonotic Disease Service
spring.cloud.gateway.routes[4].id=zoonotic-disease-service
spring.cloud.gateway.routes[4].uri=http://localhost:8086
spring.cloud.gateway.routes[4].predicates[0]=Path=/api/zoonotic-diseases/**