spring.application.name=report-service
server.port=8087

jwt.secret=DPDMS-SECRET-KEY-FOR-JWT-AUTHENTICATION-2026-SECURE

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

management.endpoints.web.exposure.include=health,info