spring.application.name=fire-service
server.port=8085

spring.datasource.url=jdbc:mysql://localhost:3306/fire_db?createDatabaseIfNotExist=true&serverTimezone=Africa/Harare
spring.datasource.username=root
spring.datasource.password=mashayz

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.customCssUrl=/swagger-custom.css
springdoc.swagger-ui.docExpansion=none
springdoc.swagger-ui.defaultModelsExpandDepth=-1
springdoc.swagger-ui.defaultModelExpandDepth=-1
springdoc.swagger-ui.displayOperationId=false
springdoc.swagger-ui.filter=false
springdoc.swagger-ui.tryItOutEnabled=true
springdoc.swagger-ui.persistAuthorization=false

management.endpoints.web.exposure.include=health,info,metrics
